Traceback (most recent call last):
  File ./PyLollygag.py, line 1010, in <module>
    main()
  File ./PyLollygag.py, line 1005, in main
    score = getSummonerMatches(ID)
  File ./PyLollygag.py, line 575, in getSummonerMatches
    currentScore = getMatchDetails(id, matchId, season, queue)
  File ./PyLollygag.py, line 683, in getMatchDetails
    firstBloodAssist = str(participant['stats']['firstBloodAssist'])
KeyError: 'firstBloodAssist'

